const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

function createFallbackGoalSuggestion(profile = {}) {
  const subject = profile.favoriteSubject || profile.subject || 'your main subject';
  return {
    title: `Focus on ${subject}`,
    description: `Spend 20-30 minutes reviewing ${subject} today. Keep it simple and work with full attention.`,
    rationale: 'A short, steady study block is easier to follow and helps build progress over time.'
  };
}

function normalizeGoalSuggestion(parsed = {}, profile = {}) {
  const fallback = createFallbackGoalSuggestion(profile);
  const isOverComplicated = (text = '') => {
    const lower = text.toLowerCase();
    return lower.includes('pyq') || lower.includes('high-weightage') || lower.includes('marking scheme') || lower.includes('official') || lower.includes('chapter') || lower.includes('questions') || lower.includes('tonight') || lower.includes('between') || lower.includes('examiner') || lower.includes('confidence') || lower.includes('practice actual') || lower.includes('board exam');
  };

  const sanitizeText = (text, fallbackText) => {
    if (typeof text !== 'string') return fallbackText;
    const cleaned = text.trim().replace(/\s+/g, ' ');
    if (!cleaned) return fallbackText;
    if (cleaned.length > 180 || isOverComplicated(cleaned)) return fallbackText;
    return cleaned;
  };

  const title = sanitizeText(parsed?.title, fallback.title);
  const description = sanitizeText(parsed?.description, fallback.description);
  const rationale = sanitizeText(parsed?.rationale, fallback.rationale);

  return { title, description, rationale };
}

app.post('/api/goal-suggest', async (req, res) => {
  try {
    const { profile = {}, prompt = '', existingGoal = '' } = req.body || {};
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: 'Gemini API key is missing.' });
    }

    const systemPrompt = `You are Neo Mentor AI, a supportive study coach for students. Create one simple, realistic daily goal that a normal student can actually follow. Keep it short, friendly, and easy to understand. Make it one small task, not a full plan. Avoid exam jargon, multiple steps, time blocks, technical wording, or overly intense language. Output JSON with title, description, rationale.`;
    const userPrompt = `Student profile: ${JSON.stringify(profile)}\nExisting goal: ${existingGoal || 'None'}\nUser request: ${prompt || 'Suggest a practical daily study goal.'}\nPlease make the suggestion beginner-friendly, realistic, and easy to complete today.`;

    let data;
    try {
      const geminiResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }] }],
          generationConfig: { temperature: 0.7, responseMimeType: 'application/json' }
        })
      });

      data = await geminiResponse.json();
      if (!geminiResponse.ok) {
        throw new Error(data?.error?.message || 'Gemini request failed.');
      }
    } catch (error) {
      const fallback = createFallbackGoalSuggestion(profile);
      return res.json({
        ...fallback,
        rationale: `${fallback.rationale} (AI service fallback)`
      });
    }

    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
    let parsed = {};
    try {
      parsed = JSON.parse(text);
    } catch (e) {
      parsed = { title: 'Study Focus Block', description: text, rationale: 'Generated by Gemini.' };
    }

    const suggestion = normalizeGoalSuggestion(parsed, profile);

    return res.json(suggestion);
  } catch (error) {
    return res.status(500).json({ error: error.message || 'Server error' });
  }
});

app.get('/health', (req, res) => {
  res.json({ ok: true, message: 'Neo Mentor API is running' });
});

const port = Number(process.env.PORT || 3000);

function startServer() {
  const candidatePorts = [Number(process.env.PORT || 3000), 3001, 3002, 3003, 3004, 3005];
  let attempt = 0;

  const tryListen = (port) => {
    const server = app.listen(port, () => {
      console.log(`Neo Mentor API listening on port ${port}`);
    });

    server.on('error', (error) => {
      if (error.code === 'EADDRINUSE' && attempt < candidatePorts.length - 1) {
        attempt += 1;
        console.warn(`Port ${port} is busy. Trying ${candidatePorts[attempt]} instead.`);
        tryListen(candidatePorts[attempt]);
      } else {
        throw error;
      }
    });
  };

  tryListen(candidatePorts[attempt]);
}

if (require.main === module) {
  startServer();
}

module.exports = { app, createFallbackGoalSuggestion, normalizeGoalSuggestion, startServer };
